<?php

namespace Stalk\AdminBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMapping;

/**
 * NewVisitedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewVisitedRepository extends EntityRepository
{   
    
    public function getUser() {
        
        $qb = $this->_em->createQueryBuilder()
             ->select('n.userId')
             ->from($this->getEntityName(), 'n')  
             ->groupBy('n.userId');                
        $query = $qb->getQuery();
        
        return $query->execute();
        
    }
    
}
